CC ?= gcc
CFLAGS ?= -Wall -Wextra -std=c11 -g
.PHONY: all clean
all:
	$(MAKE) -C demo01_sizeof
	$(MAKE) -C demo02_char_promotion
clean:
	$(MAKE) -C demo01_sizeof clean
	$(MAKE) -C demo02_char_promotion clean
