.PHONY: all clean

all:
	$(MAKE) -C demo01_extern_c
	$(MAKE) -C demo02_ref_vs_ptr
	$(MAKE) -C demo03_c_vs_cpp_polymorph
	$(MAKE) -C demo04_new_delete

clean:
	$(MAKE) -C demo01_extern_c clean
	$(MAKE) -C demo02_ref_vs_ptr clean
	$(MAKE) -C demo03_c_vs_cpp_polymorph clean
	$(MAKE) -C demo04_new_delete clean
